[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
alter_escrow = "AY1t5psHSBUX3fn8nve6WqkYS7zLRu1KyLZn61yGvBoc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx jest --preset ts-jest"
