[package]
name = "create-metadata"
version = "0.1.0"
edition = "2021"

[dependencies]
mpl-token-metadata = "4.1.2"
dotenv = "0.15.0"
serde = "1.0.208"
serde_json = "1.0.125"
tokio = "1.39.3"
solana-program = "1.18.2"
solana-sdk = "1.18.2"
solana-client = "1.18.2"